#bidding zones from entso-e
all_zones = [
    'DE_50HZ',
    'AL',
    'DE_AMPRION',
    'AT',
    'BY',
    'BE',
    'BA',
    'BG',
    'CZ_DE_SK',
    'HR',
    'CWE',
    'CY',
    'CZ',
    'DE_AT_LU',
    'DE_LU',
    'DK',
    'DK_1',
    'DK_1_NO_1',
    'DK_2',
    'DK_CA',
    'EE',
    'FI',
    'MK',
    'FR',
    'DE',
    'GR',
    'HU',
    'IS',
    'IE_SEM',
    'IE',
    'IT',
    'IT_SACO_AC',
    'IT_CALA',
    'IT_SACO_DC',
    'IT_BRNN',
    'IT_CNOR',
    'IT_CSUD',
    'IT_FOGN',
    'IT_GR',
    'IT_MACRO_NORTH',
    'IT_MACRO_SOUTH',
    'IT_MALTA',
    'IT_NORD',
    'IT_NORD_AT',
    'IT_NORD_CH',
    'IT_NORD_FR',
    'IT_NORD_SI',
    'IT_PRGP',
    'IT_ROSN',
    'IT_SARD',
    'IT_SICI',
    'IT_SUD',
    'RU_KGD',
    'LV',
    'LT',
    'LU',
    'LU_BZN',
    'MT',
    'ME',
    'GB',
    'GB_IFA',
    'GB_IFA2',
    'GB_ELECLINK',
    'UK',
    'NL',
    'NO_1',
    'NO_1A',
    'NO_2',
    'NO_2_NSL',
    'NO_2A',
    'NO_3',
    'NO_4',
    'NO_5',
    'NO',
    'PL_CZ',
    'PL',
    'PT',
    'MD',
    'RO',
    'RU',
    'SE_1',
    'SE_2',
    'SE_3',
    'SE_4',
    'RS',
    'SK',
    'SI',
    'GB_NIR',
    'ES',
    'SE',
    'CH',
    'DE_TENNET',
    'DE_TRANSNET',
    'TR',
    'UA',
    'UA_DOBTPP',
    'UA_BEI',
    'UA_IPS',
    'XK'
]

bidding_zones = [
    'AT',
    'BE',
    'BG',
    'HR',
    'CY',
    'CZ',
    'DK_1',
    'DK_2',
    'EE',
    'FI',
    'FR',
    'DE_LU',
    'GR',
    'HU',
    'IE_SEM',
    'IT_NORD',
    'IT_CNOR',
    'IT_CSUD',
    'IT_SUD',
    'IT_CALA',
    'IT_SICI',
    'IT_SARD',
    'IT_SACO_AC',
    'IT_SACO_DC',
    'LV',
    'LT',
    'MT',
    'NL',
    'PL',
    'PT',
    'RO',
    'SK',
    'SI',
    'ES',
    'SE_1',
    'SE_2',
    'SE_3',
    'SE_4',
    'CH',
    'NO_1',
    'NO_2',
    'NO_3',
    'NO_4',
    'NO_5',
    'GB',
]

PSRTYPE_MAPPINGS = {
    'B01': 'Biomass',
    'B02': 'Fossil Brown coal/Lignite',
    'B03': 'Fossil Coal-derived gas',
    'B04': 'Fossil Gas',
    'B05': 'Fossil Hard coal',
    'B06': 'Fossil Oil',
    'B07': 'Fossil Oil shale',
    'B08': 'Fossil Peat',
    'B09': 'Geothermal',
    'B10': 'Hydro Pumped Storage',
    'B11': 'Hydro Run-of-river and poundage',
    'B12': 'Hydro Water Reservoir',
    'B13': 'Marine',
    'B14': 'Nuclear',
    'B15': 'Other renewable',
    'B16': 'Solar',
    'B17': 'Waste',
    'B18': 'Wind Offshore',
    'B19': 'Wind Onshore',
    'B20': 'Other',
}

psr_types = [
    'B01',
    'B02',
    'B03',
    'B04',
    'B05',
    'B06',
    'B07',
    'B08',
    'B09',
    'B10',
    'B11',
    'B12',
    'B13',
    'B14',
    'B15',
    'B16',
    'B17',
    'B18',
    'B19',
    'B20',
]

# neighbouring bidding zones that have cross_border flows
NEIGHBOURS = {
    'AT': ['CZ', 'DE_LU', 'CH', 'IT_NORD', 'SI', 'HU', 'SK'],
    'BE': ['NL', 'FR', 'GB', 'DE_LU'],
    'BG': ['GR', 'MK', 'RO', 'RS', 'TR'],
    'HR': ['BA', 'HU', 'RS', 'SI'],
    'CY': [],
    'CZ': ['AT', 'DE_AT_LU', 'DE_LU', 'PL', 'SK'],
    'DK_1': ['DE_AT_LU', 'DE_LU', 'DK_2', 'NO_2', 'SE_3', 'NL'],
    'DK_2': ['DE_AT_LU', 'DE_LU', 'DK_1', 'SE_4'],
    'EE': ['FI', 'LV', 'RU'], #FI?
    'FI': ['EE', 'NO_4', 'RU', 'SE_1', 'SE_3'], #EE?
    'FR': ['BE', 'CH', 'DE_AT_LU', 'DE_LU', 'ES', 'GB', 'IT_NORD'], #'IT_NORD_FR'?
    'DE_LU': ['AT', 'BE', 'CH', 'CZ', 'DK_1', 'DK_2', 'FR', 'NO_2', 'NL', 'PL', 'SE_4'], #NO2?
    'GR': ['AL', 'BG', 'MK', 'TR'],
    'HU': ['AT', 'SI', 'HR', 'RO', 'RS', 'SK', 'UA'],
    'IE_SEM': ['GB'],
    'IT_NORD': ['CH', 'DE_AT_LU', 'FR', 'SI', 'AT', 'IT_CNOR'], #DEATLU
    'IT_CNOR': ['IT_NORD', 'IT_CSUD', 'IT_SARD'], #IT_SARD?
    'IT_CSUD': ['IT_CNOR', 'IT_SARD', 'IT_SUD'], #IT_SARD?
    'IT_SUD': ['IT_CSUD', 'IT_CALA'], #check
    'IT_CALA': ['IT_SICI', 'IT_SUD'],
    'IT_SICI': ['IT_CALA', 'MT'],
    'IT_SARD': ['IT_SACO_AC','IT_SACO_DC','IT_CNOR', 'IT_CSUD'],#'IT_CNOR', 'IT_CSUD'?
    'IT_SACO_AC': ['IT_SARD', 'IT_SACO_DC'],
    'IT_SACO_DC': ['IT_SARD', 'IT_SACO_AC'],
    'LV': ['EE', 'LT', 'RU','BY'],
    'LT': ['BY', 'LV', 'PL', 'RU_KGD', 'SE_4'],
    'MT': ['IT_SICI'],
    'NL': ['BE', 'DE_LU', 'GB', 'NO_2', 'DK_1'],
    'PL': ['CZ', 'DE_AT_LU', 'DE_LU', 'LT', 'SE_4', 'SK', 'UA','BY','RU_KGD'],
    'PT': ['ES'],
    'RO': ['BG', 'HU', 'RS', 'UA', 'MD'],
    'SK': ['CZ', 'HU','AT', 'PL', 'UA'],
    'SI': ['AT', 'DE_AT_LU','AT', 'HR', 'IT_NORD', 'HU'],
    'ES': ['FR', 'PT'],
    'SE_1': ['FI', 'NO_4', 'SE_2'],
    'SE_2': ['NO_3', 'NO_4', 'SE_1', 'SE_3'],
    'SE_3': ['DK_1', 'FI', 'NO_1', 'SE_2', 'SE_4'],
    'SE_4': ['DE_AT_LU', 'DE_LU', 'DK_2', 'LT', 'PL', 'SE_3'],
    'CH': ['AT', 'DE_AT_LU', 'DE_LU', 'FR', 'IT_NORD'],
    'NO_1': ['NO_2', 'NO_3', 'NO_5', 'SE_3'],
    'NO_2': ['DE_LU', 'DK_1', 'NL', 'NO_1', 'NO_5', 'GB'],#DE_LU GB?
    'NO_3': ['NO_1', 'NO_4', 'NO_5', 'SE_2'],
    'NO_4': ['SE_2', 'FI', 'NO_3', 'SE_1', 'RU'],
    'NO_5': ['NO_1', 'NO_2', 'NO_3'],
    'GB': ['BE', 'FR', 'IE_SEM', 'NL', 'NO_2'],
}

def get_bidding_zones():
    return bidding_zones

def get_psr_type():
    return psr_types

def lookup_psr_type(psr):
    return PSRTYPE_MAPPINGS[psr]

def get_neighbors(zone_code):
    return NEIGHBOURS[zone_code]